---
- name: Install git
  yum:
    name: git
    state: latest
  tags: git
  
- name: install docker
  yum:
    name: docker
    state: latest
  tags: docker

- name: start docker
  service:
    name: docker
    state: started
  tags: docker